name: tox python package

on:
  # This tox workflow is only triggered on the PR and push of main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allows running manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
      
    - name: Python Linter
      # You may pin to the exact commit or the version.
      # uses: sunnysid3up/python-linter@93076bd8f740f062069291d738fc70c1b4171c1d
      uses: sunnysid3up/python-linter@v0.1-beta.7
      with:
        # Source file or directory
        source: "revclassifier" 
        # Set strictness for lint [low, medium, high]
        strict: "Medium" # optional, default is medium
        # Mypy options
        mypy-options: "" # optional, default is 
        # Pylint options
        pylint-options: "" # optional, default is 
        # Black options
        black-options: "" # optional, default is 
        # Isort options
        isort-options: "" # optional, default is 
        # Confirm if source is a Django project
        django: false # optional
